name: flutter_appuse_time
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_slidable: ^3.0.0
  cupertino_icons: ^1.0.8
  device_apps: 
    path: ./package/device_apps-2.2.0
  app_usage: ^4.0.1
  intl: ^0.18.0
  fl_chart: ^0.71.0
  flutter_local_notifications: ^19.1.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  flutter_background_service: ^5.1.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "icon2.png"
  adaptive_icon_background: "#4E6AF3"
  adaptive_icon_foreground: "icon2.png"

flutter:
  uses-material-design: true